/*
    AUTO-GENERATED MINIAUDIO INTERNAL WRAPPER FUNCTIONS
    This file is automatically generated by gen_csharp.py
    DO NOT EDIT MANUALLY

    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead.
*/

#ifndef MINIAUDIO_CSHARP_INTERNAL_WRAPPERS_H
#define MINIAUDIO_CSHARP_INTERNAL_WRAPPERS_H

#define MA_NO_IMPLEMENTATION
#include "miniaudio.h"

// For Emscripten builds, these functions need to be exported
#ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #define MINIAUDIO_EXPORT EMSCRIPTEN_KEEPALIVE
#else
    #define MINIAUDIO_EXPORT
#endif

// ========== MiniAudio (ma_) ===========

MINIAUDIO_EXPORT void ma_log_callback_init_internal(ma_log_callback* result, ma_log_callback_proc onLog, void * pUserData) {
    *result = ma_log_callback_init(onLog, pUserData);
}

MINIAUDIO_EXPORT void ma_biquad_config_init_internal(ma_biquad_config* result, ma_format format, ma_uint32 channels, double b0, double b1, double b2, double a0, double a1, double a2) {
    *result = ma_biquad_config_init(format, channels, b0, b1, b2, a0, a1, a2);
}

MINIAUDIO_EXPORT void ma_lpf1_config_init_internal(ma_lpf1_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency) {
    *result = ma_lpf1_config_init(format, channels, sampleRate, cutoffFrequency);
}

MINIAUDIO_EXPORT void ma_lpf2_config_init_internal(ma_lpf2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, double q) {
    *result = ma_lpf2_config_init(format, channels, sampleRate, cutoffFrequency, q);
}

MINIAUDIO_EXPORT void ma_lpf_config_init_internal(ma_lpf_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order) {
    *result = ma_lpf_config_init(format, channels, sampleRate, cutoffFrequency, order);
}

MINIAUDIO_EXPORT void ma_hpf1_config_init_internal(ma_hpf1_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency) {
    *result = ma_hpf1_config_init(format, channels, sampleRate, cutoffFrequency);
}

MINIAUDIO_EXPORT void ma_hpf2_config_init_internal(ma_hpf2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, double q) {
    *result = ma_hpf2_config_init(format, channels, sampleRate, cutoffFrequency, q);
}

MINIAUDIO_EXPORT void ma_hpf_config_init_internal(ma_hpf_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order) {
    *result = ma_hpf_config_init(format, channels, sampleRate, cutoffFrequency, order);
}

MINIAUDIO_EXPORT void ma_bpf2_config_init_internal(ma_bpf2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, double q) {
    *result = ma_bpf2_config_init(format, channels, sampleRate, cutoffFrequency, q);
}

MINIAUDIO_EXPORT void ma_bpf_config_init_internal(ma_bpf_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order) {
    *result = ma_bpf_config_init(format, channels, sampleRate, cutoffFrequency, order);
}

MINIAUDIO_EXPORT void ma_notch2_config_init_internal(ma_notch2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double q, double frequency) {
    *result = ma_notch2_config_init(format, channels, sampleRate, q, frequency);
}

MINIAUDIO_EXPORT void ma_peak2_config_init_internal(ma_peak2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double q, double frequency) {
    *result = ma_peak2_config_init(format, channels, sampleRate, gainDB, q, frequency);
}

MINIAUDIO_EXPORT void ma_loshelf2_config_init_internal(ma_loshelf2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double shelfSlope, double frequency) {
    *result = ma_loshelf2_config_init(format, channels, sampleRate, gainDB, shelfSlope, frequency);
}

MINIAUDIO_EXPORT void ma_hishelf2_config_init_internal(ma_hishelf2_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double shelfSlope, double frequency) {
    *result = ma_hishelf2_config_init(format, channels, sampleRate, gainDB, shelfSlope, frequency);
}

MINIAUDIO_EXPORT void ma_delay_config_init_internal(ma_delay_config* result, ma_uint32 channels, ma_uint32 sampleRate, ma_uint32 delayInFrames, float decay) {
    *result = ma_delay_config_init(channels, sampleRate, delayInFrames, decay);
}

MINIAUDIO_EXPORT void ma_gainer_config_init_internal(ma_gainer_config* result, ma_uint32 channels, ma_uint32 smoothTimeInFrames) {
    *result = ma_gainer_config_init(channels, smoothTimeInFrames);
}

MINIAUDIO_EXPORT void ma_panner_config_init_internal(ma_panner_config* result, ma_format format, ma_uint32 channels) {
    *result = ma_panner_config_init(format, channels);
}

MINIAUDIO_EXPORT void ma_fader_config_init_internal(ma_fader_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate) {
    *result = ma_fader_config_init(format, channels, sampleRate);
}

MINIAUDIO_EXPORT void ma_spatializer_listener_config_init_internal(ma_spatializer_listener_config* result, ma_uint32 channelsOut) {
    *result = ma_spatializer_listener_config_init(channelsOut);
}

MINIAUDIO_EXPORT void ma_spatializer_listener_get_position_internal(ma_vec3f* result, const ma_spatializer_listener * pListener) {
    *result = ma_spatializer_listener_get_position(pListener);
}

MINIAUDIO_EXPORT void ma_spatializer_listener_get_direction_internal(ma_vec3f* result, const ma_spatializer_listener * pListener) {
    *result = ma_spatializer_listener_get_direction(pListener);
}

MINIAUDIO_EXPORT void ma_spatializer_listener_get_velocity_internal(ma_vec3f* result, const ma_spatializer_listener * pListener) {
    *result = ma_spatializer_listener_get_velocity(pListener);
}

MINIAUDIO_EXPORT void ma_spatializer_listener_get_world_up_internal(ma_vec3f* result, const ma_spatializer_listener * pListener) {
    *result = ma_spatializer_listener_get_world_up(pListener);
}

MINIAUDIO_EXPORT void ma_spatializer_config_init_internal(ma_spatializer_config* result, ma_uint32 channelsIn, ma_uint32 channelsOut) {
    *result = ma_spatializer_config_init(channelsIn, channelsOut);
}

MINIAUDIO_EXPORT void ma_spatializer_get_position_internal(ma_vec3f* result, const ma_spatializer * pSpatializer) {
    *result = ma_spatializer_get_position(pSpatializer);
}

MINIAUDIO_EXPORT void ma_spatializer_get_direction_internal(ma_vec3f* result, const ma_spatializer * pSpatializer) {
    *result = ma_spatializer_get_direction(pSpatializer);
}

MINIAUDIO_EXPORT void ma_spatializer_get_velocity_internal(ma_vec3f* result, const ma_spatializer * pSpatializer) {
    *result = ma_spatializer_get_velocity(pSpatializer);
}

MINIAUDIO_EXPORT void ma_linear_resampler_config_init_internal(ma_linear_resampler_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut) {
    *result = ma_linear_resampler_config_init(format, channels, sampleRateIn, sampleRateOut);
}

MINIAUDIO_EXPORT void ma_resampler_config_init_internal(ma_resampler_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut, ma_resample_algorithm algorithm) {
    *result = ma_resampler_config_init(format, channels, sampleRateIn, sampleRateOut, algorithm);
}

MINIAUDIO_EXPORT void ma_channel_converter_config_init_internal(ma_channel_converter_config* result, ma_format format, ma_uint32 channelsIn, const ma_channel * pChannelMapIn, ma_uint32 channelsOut, const ma_channel * pChannelMapOut, ma_channel_mix_mode mixingMode) {
    *result = ma_channel_converter_config_init(format, channelsIn, pChannelMapIn, channelsOut, pChannelMapOut, mixingMode);
}

MINIAUDIO_EXPORT void ma_data_converter_config_init_default_internal(ma_data_converter_config* result) {
    *result = ma_data_converter_config_init_default();
}

MINIAUDIO_EXPORT void ma_data_converter_config_init_internal(ma_data_converter_config* result, ma_format formatIn, ma_format formatOut, ma_uint32 channelsIn, ma_uint32 channelsOut, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut) {
    *result = ma_data_converter_config_init(formatIn, formatOut, channelsIn, channelsOut, sampleRateIn, sampleRateOut);
}

MINIAUDIO_EXPORT void ma_data_source_config_init_internal(ma_data_source_config* result) {
    *result = ma_data_source_config_init();
}

MINIAUDIO_EXPORT void ma_audio_buffer_config_init_internal(ma_audio_buffer_config* result, ma_format format, ma_uint32 channels, ma_uint64 sizeInFrames, const void * pData, const ma_allocation_callbacks * pAllocationCallbacks) {
    *result = ma_audio_buffer_config_init(format, channels, sizeInFrames, pData, pAllocationCallbacks);
}

MINIAUDIO_EXPORT void ma_paged_audio_buffer_config_init_internal(ma_paged_audio_buffer_config* result, ma_paged_audio_buffer_data * pData) {
    *result = ma_paged_audio_buffer_config_init(pData);
}

MINIAUDIO_EXPORT void ma_slot_allocator_config_init_internal(ma_slot_allocator_config* result, ma_uint32 capacity) {
    *result = ma_slot_allocator_config_init(capacity);
}

MINIAUDIO_EXPORT void ma_job_init_internal(ma_job* result, ma_uint16 code) {
    *result = ma_job_init(code);
}

MINIAUDIO_EXPORT void ma_job_queue_config_init_internal(ma_job_queue_config* result, ma_uint32 flags, ma_uint32 capacity) {
    *result = ma_job_queue_config_init(flags, capacity);
}

MINIAUDIO_EXPORT void ma_device_job_thread_config_init_internal(ma_device_job_thread_config* result) {
    *result = ma_device_job_thread_config_init();
}

MINIAUDIO_EXPORT void ma_context_config_init_internal(ma_context_config* result) {
    *result = ma_context_config_init();
}

MINIAUDIO_EXPORT void ma_device_config_init_internal(ma_device_config* result, ma_device_type deviceType) {
    *result = ma_device_config_init(deviceType);
}

MINIAUDIO_EXPORT void ma_decoding_backend_config_init_internal(ma_decoding_backend_config* result, ma_format preferredFormat, ma_uint32 seekPointCount) {
    *result = ma_decoding_backend_config_init(preferredFormat, seekPointCount);
}

MINIAUDIO_EXPORT void ma_decoder_config_init_internal(ma_decoder_config* result, ma_format outputFormat, ma_uint32 outputChannels, ma_uint32 outputSampleRate) {
    *result = ma_decoder_config_init(outputFormat, outputChannels, outputSampleRate);
}

MINIAUDIO_EXPORT void ma_decoder_config_init_default_internal(ma_decoder_config* result) {
    *result = ma_decoder_config_init_default();
}

MINIAUDIO_EXPORT void ma_encoder_config_init_internal(ma_encoder_config* result, ma_encoding_format encodingFormat, ma_format format, ma_uint32 channels, ma_uint32 sampleRate) {
    *result = ma_encoder_config_init(encodingFormat, format, channels, sampleRate);
}

MINIAUDIO_EXPORT void ma_waveform_config_init_internal(ma_waveform_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, ma_waveform_type type, double amplitude, double frequency) {
    *result = ma_waveform_config_init(format, channels, sampleRate, type, amplitude, frequency);
}

MINIAUDIO_EXPORT void ma_pulsewave_config_init_internal(ma_pulsewave_config* result, ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double dutyCycle, double amplitude, double frequency) {
    *result = ma_pulsewave_config_init(format, channels, sampleRate, dutyCycle, amplitude, frequency);
}

MINIAUDIO_EXPORT void ma_noise_config_init_internal(ma_noise_config* result, ma_format format, ma_uint32 channels, ma_noise_type type, ma_int32 seed, double amplitude) {
    *result = ma_noise_config_init(format, channels, type, seed, amplitude);
}

MINIAUDIO_EXPORT void ma_resource_manager_pipeline_notifications_init_internal(ma_resource_manager_pipeline_notifications* result) {
    *result = ma_resource_manager_pipeline_notifications_init();
}

MINIAUDIO_EXPORT void ma_resource_manager_data_source_config_init_internal(ma_resource_manager_data_source_config* result) {
    *result = ma_resource_manager_data_source_config_init();
}

MINIAUDIO_EXPORT void ma_resource_manager_config_init_internal(ma_resource_manager_config* result) {
    *result = ma_resource_manager_config_init();
}

MINIAUDIO_EXPORT void ma_node_config_init_internal(ma_node_config* result) {
    *result = ma_node_config_init();
}

MINIAUDIO_EXPORT void ma_node_graph_config_init_internal(ma_node_graph_config* result, ma_uint32 channels) {
    *result = ma_node_graph_config_init(channels);
}

MINIAUDIO_EXPORT void ma_data_source_node_config_init_internal(ma_data_source_node_config* result, ma_data_source * pDataSource) {
    *result = ma_data_source_node_config_init(pDataSource);
}

MINIAUDIO_EXPORT void ma_splitter_node_config_init_internal(ma_splitter_node_config* result, ma_uint32 channels) {
    *result = ma_splitter_node_config_init(channels);
}

MINIAUDIO_EXPORT void ma_biquad_node_config_init_internal(ma_biquad_node_config* result, ma_uint32 channels, float b0, float b1, float b2, float a0, float a1, float a2) {
    *result = ma_biquad_node_config_init(channels, b0, b1, b2, a0, a1, a2);
}

MINIAUDIO_EXPORT void ma_lpf_node_config_init_internal(ma_lpf_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order) {
    *result = ma_lpf_node_config_init(channels, sampleRate, cutoffFrequency, order);
}

MINIAUDIO_EXPORT void ma_hpf_node_config_init_internal(ma_hpf_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order) {
    *result = ma_hpf_node_config_init(channels, sampleRate, cutoffFrequency, order);
}

MINIAUDIO_EXPORT void ma_bpf_node_config_init_internal(ma_bpf_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order) {
    *result = ma_bpf_node_config_init(channels, sampleRate, cutoffFrequency, order);
}

MINIAUDIO_EXPORT void ma_notch_node_config_init_internal(ma_notch_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double q, double frequency) {
    *result = ma_notch_node_config_init(channels, sampleRate, q, frequency);
}

MINIAUDIO_EXPORT void ma_peak_node_config_init_internal(ma_peak_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double q, double frequency) {
    *result = ma_peak_node_config_init(channels, sampleRate, gainDB, q, frequency);
}

MINIAUDIO_EXPORT void ma_loshelf_node_config_init_internal(ma_loshelf_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double q, double frequency) {
    *result = ma_loshelf_node_config_init(channels, sampleRate, gainDB, q, frequency);
}

MINIAUDIO_EXPORT void ma_hishelf_node_config_init_internal(ma_hishelf_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double q, double frequency) {
    *result = ma_hishelf_node_config_init(channels, sampleRate, gainDB, q, frequency);
}

MINIAUDIO_EXPORT void ma_delay_node_config_init_internal(ma_delay_node_config* result, ma_uint32 channels, ma_uint32 sampleRate, ma_uint32 delayInFrames, float decay) {
    *result = ma_delay_node_config_init(channels, sampleRate, delayInFrames, decay);
}

MINIAUDIO_EXPORT void ma_engine_node_config_init_internal(ma_engine_node_config* result, ma_engine * pEngine, ma_engine_node_type type, ma_uint32 flags) {
    *result = ma_engine_node_config_init(pEngine, type, flags);
}

MINIAUDIO_EXPORT void ma_sound_config_init_internal(ma_sound_config* result) {
    *result = ma_sound_config_init();
}

MINIAUDIO_EXPORT void ma_sound_config_init_2_internal(ma_sound_config* result, ma_engine * pEngine) {
    *result = ma_sound_config_init_2(pEngine);
}

MINIAUDIO_EXPORT void ma_sound_group_config_init_internal(ma_sound_group_config* result) {
    *result = ma_sound_group_config_init();
}

MINIAUDIO_EXPORT void ma_sound_group_config_init_2_internal(ma_sound_group_config* result, ma_engine * pEngine) {
    *result = ma_sound_group_config_init_2(pEngine);
}

MINIAUDIO_EXPORT void ma_engine_config_init_internal(ma_engine_config* result) {
    *result = ma_engine_config_init();
}

MINIAUDIO_EXPORT void ma_engine_listener_get_position_internal(ma_vec3f* result, const ma_engine * pEngine, ma_uint32 listenerIndex) {
    *result = ma_engine_listener_get_position(pEngine, listenerIndex);
}

MINIAUDIO_EXPORT void ma_engine_listener_get_direction_internal(ma_vec3f* result, const ma_engine * pEngine, ma_uint32 listenerIndex) {
    *result = ma_engine_listener_get_direction(pEngine, listenerIndex);
}

MINIAUDIO_EXPORT void ma_engine_listener_get_velocity_internal(ma_vec3f* result, const ma_engine * pEngine, ma_uint32 listenerIndex) {
    *result = ma_engine_listener_get_velocity(pEngine, listenerIndex);
}

MINIAUDIO_EXPORT void ma_engine_listener_get_world_up_internal(ma_vec3f* result, const ma_engine * pEngine, ma_uint32 listenerIndex) {
    *result = ma_engine_listener_get_world_up(pEngine, listenerIndex);
}

MINIAUDIO_EXPORT void ma_sound_get_direction_to_listener_internal(ma_vec3f* result, const ma_sound * pSound) {
    *result = ma_sound_get_direction_to_listener(pSound);
}

MINIAUDIO_EXPORT void ma_sound_get_position_internal(ma_vec3f* result, const ma_sound * pSound) {
    *result = ma_sound_get_position(pSound);
}

MINIAUDIO_EXPORT void ma_sound_get_direction_internal(ma_vec3f* result, const ma_sound * pSound) {
    *result = ma_sound_get_direction(pSound);
}

MINIAUDIO_EXPORT void ma_sound_get_velocity_internal(ma_vec3f* result, const ma_sound * pSound) {
    *result = ma_sound_get_velocity(pSound);
}

MINIAUDIO_EXPORT void ma_sound_group_get_direction_to_listener_internal(ma_vec3f* result, const ma_sound_group * pGroup) {
    *result = ma_sound_group_get_direction_to_listener(pGroup);
}

MINIAUDIO_EXPORT void ma_sound_group_get_position_internal(ma_vec3f* result, const ma_sound_group * pGroup) {
    *result = ma_sound_group_get_position(pGroup);
}

MINIAUDIO_EXPORT void ma_sound_group_get_direction_internal(ma_vec3f* result, const ma_sound_group * pGroup) {
    *result = ma_sound_group_get_direction(pGroup);
}

MINIAUDIO_EXPORT void ma_sound_group_get_velocity_internal(ma_vec3f* result, const ma_sound_group * pGroup) {
    *result = ma_sound_group_get_velocity(pGroup);
}

#endif // MINIAUDIO_CSHARP_INTERNAL_WRAPPERS_H
