/*=== C# BINDING HELPERS =====================================================
    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead. The C# binding generator automatically creates wrappers
    that call these functions on WebAssembly builds while using the regular functions
    on other platforms.

    The internal wrapper functions are auto-generated by bindgen/gen_csharp.py
    and included from miniaudio_csharp_internal_wrappers.h
============================================================================*/

// Include auto-generated internal wrapper functions for miniaudio C# bindings.
// MA_IMPLEMENTATION is undefined here so that the miniaudio.h included inside
// miniaudio_csharp_internal_wrappers.h only provides declarations (not the
// full implementation, which is compiled in miniaudio.c).
#undef MA_IMPLEMENTATION
#include "miniaudio_csharp_internal_wrappers.h"
